//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba_doublevpartners_ENL.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personas()
        {
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public long Identificador { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public long Numero_de_identificacion { get; set; }
        public string Email { get; set; }
        public string Tipo_identificacion { get; set; }
        public Nullable<System.DateTime> Fecha_de_creación { get; set; }
        public string Nombres_Apellidos { get; set; }
        public string Tipo_NumeroIdentificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
